name: Build Documentation

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        path: docs
    - name: Checkout live docs repo
      uses: actions/checkout@v1
      with:
        repository: sebastianlundquist/poker-docs
        ref: master
        path: docs/live
    - name: Clear live docs repo
      run: rm -rf *
    - name: Checkout poker
      uses: actions/checkout@v1
      with:
        repository: sebastianlundquist/poker
        ref: master
        path: docs/poker

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Get mono
      run: |
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt-get update
        sudo apt-get install mono-complete --yes
    - name: Get docfx
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d docs docfx.zip

    - name: Build docs
      run: |
        ls
        cd docs
        ls
        mono docfx build
      
    - name: Commit and push
      run: |
        cd live
        git config --global user.email "dev.sebastian.lundquist@gmail.com"
        git config --global user.name "Automated System"
        git add .
        git commit -m "Automated update" --author $GITHUB_ACTOR
        header=$(echo -n "ad-m:$" | base64)
        git -c http.extraheader="AUTHORIZATION: basic $header" push origin HEAD:master
